export const STORAGE_KEYS = {
    TOKEN: 'TOKEN',
    USER: 'USER',
    ACTIVE_RACE: 'ACTIVE_RACE',
    SCHEDULE: 'SCHEDULE',
    RACE: 'RACE',
    RACE_LOGS: 'RACE_LOGS',

    RACE_DURATION_STATS: 'RACE_DURATION_STATS',
    DRIVER_STATS: 'DRIVER_STATS',
    STINT_STATS: 'STINT_STATS',

}